language: ruby
rvm:
- 2.0.0

branches:
  only:
  - develop
before_install:
- gem update
before_script:
- git config --global user.name "Antonio Cabrera"
- git config --global user.email "antonio.cabreraglz@gmail.com"
- git clone --quiet --branch=master https://${GH_TOKEN}@github.com/antonio-cabreraglz/drunken-octo-sansa.git _site

after_success:
- bundle exec rake deploy

env:
  global:
    secure: v11fpxT5YnKQPBJKF3siSqZWpMMGzoFe2JtR0AwXGzwSR9ie+Tihka/zZla2+AOF7qC5nmYhrveWa3VqAD7w5M0dtQosOarq1LY17vTEGGMhYo3v5dYwXzVXOFZPIgDOa6VhXm9tftnj9oFkwukV5fKgm5fxvJcrJQzywypdvEI=
